# Generated by Django 3.1.13 on 2021-08-21 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_auto_20210821_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_num',
            field=models.IntegerField(default=True, max_length=9),
            preserve_default=False,
        ),
    ]
